config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'

  patch '/save', to: 'users#save_keys', as: 'save_keys'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/crypt_concern.rb
##
# This module sole purpose it to encrypt/decrypt sensitive data which stores
# in our database.
# Located in /models/concerns/crypt_concern

module CryptConcern
  extend ActiveSupport::Concern

  def crypt
    len = ActiveSupport::MessageEncryptor.key_len
    # Ensute to have a :salt key in your credentials
    # with: EDITOR='vi' bundle exec rails credentials:edit
    salt = Rails.application.credentials[:salt]
    key = ActiveSupport::KeyGenerator.new(salt).generate_key(salt, len)

    # Value of last executed line is returned
    ActiveSupport::MessageEncryptor.new(key)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Some basic validation when we call our save method only.
  # See more: https://guides.rubyonrails.org/v3.2/active_record_validations_callbacks.html
  validates :consumer_key, presence: true, on: :save_keys
  validates :consumer_secret, presence: true, on: :save_keys

  # This is how we reuse a shared method in our rails model (crypt)
  include CryptConcern

  # HACK! We use the user model as an example. Normally you would use another model
  # in a situation like this. When a new user is created or updated,
  # this callback will get triggered
  before_save :encrypted_consumer_key_and_secret,
    if: Proc.new { |user| !user.consumer_key.nil? }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private
    def encrypted_consumer_key_and_secret
      encrypted_key = crypt.encrypt_and_sign(self.consumer_key)
      encrypted_secret = crypt.encrypt_and_sign(self.consumer_secret)
      self.consumer_key = encrypted_key
      self.consumer_secret = encrypted_secret
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  include CryptConcern

  # GET /
  def index
    @user = current_user
  end

  # PATCH /save
  def save_keys
    user = current_user

    # To see the decrypted value:
    # puts crypt.decrypt_and_verify(user.consumer_key)
    # will print the value in your terminal.

    # If all is saved, return to homepage
    # To use a falsh notice, use the regular if block: if ... end
    user.update_attributes(user_params) and return redirect_to root_path

    # Normally this action would be an :edit
    # Ensure you have an edit method before changing.
    render action: :index
  end

  private
    def user_params
      params.require(:user).permit(:consumer_key, :consumer_secret)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A simple way to encrypt and decrypt in Rails 5.2 - Revisited</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_show_keys.html.erb
<div class="show-keys">
  <div class="show-keys__inner">
    <ul>
      <li>
        Encrypted Consumer Key: <span class="pink"><%= @user.consumer_key %></span>
      </li>
      <li>
        Encrypted Consumer Secret: <span class="pink"><%= @user.consumer_secret %></span>
      </li>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, url: save_keys_path, :html => { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :consumer_key, 'Consumer Key' %>
    <%= f.password_field :consumer_key, placeholder: "Paste your Consumer Key", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :consumer_secret, 'Consumer Secret' %>
    <%= f.password_field :consumer_secret, placeholder: "Paste your Consumer Secret", required: true %>
  </div>
  <div class="form-group button">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="upload">
  <div class="upload__inner">
    <h1 class="upload__inner--center">A simple way to encrypt and decrypt in Rails 5.2 - Revisited</h1>
    <div class="upload__inner__svg upload__inner--center">
        <%= render 'shared/auth_svg' %>
    </div>
    <%= render 'form' %>
    <%= render 'shared/show_keys' if @user.consumer_key.present? %>
  </div>
</div>